"""initial

Revision ID: a60d606c406a
Revises:
Create Date: 2025-04-05 18:19:38.037051

"""
from typing import (
    Sequence,
    Union,
)


# import sqlalchemy as sa
# from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'a60d606c406a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
