"""add_booth_model

Revision ID: 0ec488a02bfc
Revises: 639616586b91
Create Date: 2025-07-05 17:36:03.067437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ec488a02bfc'
down_revision: Union[str, None] = '639616586b91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('booths',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tags', sa.ARRAY(sa.String(length=50)), nullable=True),
    sa.Column('status', sa.Enum('APPROVED', 'PENDING', 'SUSPEND', name='booth_status_enum'), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_booths_id'), 'booths', ['id'], unique=False)
    op.create_index(op.f('ix_booths_owner_id'), 'booths', ['owner_id'], unique=False)
    op.create_index(op.f('ix_booths_status'), 'booths', ['status'], unique=False)
    op.create_index(op.f('ix_booths_title'), 'booths', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_booths_title'), table_name='booths')
    op.drop_index(op.f('ix_booths_status'), table_name='booths')
    op.drop_index(op.f('ix_booths_owner_id'), table_name='booths')
    op.drop_index(op.f('ix_booths_id'), table_name='booths')
    op.drop_table('booths')
    # ### end Alembic commands ###
